const hotels=[{id:1,name:'Sea View Palace',city:'Goa',price:4899,rating:4.6,reviews:128,description:'Bright sea-facing rooms with breakfast, beach access, and a rooftop pool for sunset views.',amenities:['Breakfast','Pool','Free WiFi','Airport pickup'],images:['https://picsum.photos/seed/goa1/600/400','https://picsum.photos/seed/goa2/600/400','https://picsum.photos/seed/goa3/600/400']},{id:2,name:'Snow Crest Inn',city:'Manali',price:3599,rating:4.3,reviews:84,description:'Warm wooden interiors, mountain views, heater service, and quick access to the mall road.',amenities:['Mountain View','Parking','Heater','Bonfire'],images:['https://picsum.photos/seed/manali1/600/400','https://picsum.photos/seed/manali2/600/400','https://picsum.photos/seed/manali3/600/400']},{id:3,name:'Amber Courtyard',city:'Jaipur',price:4299,rating:4.7,reviews:176,description:'Heritage-style stay with courtyard dining, handpicked decor, and easy fort sightseeing.',amenities:['Breakfast','Heritage stay','Restaurant','City tour'],images:['https://picsum.photos/seed/jaipur1/600/400','https://picsum.photos/seed/jaipur2/600/400','https://picsum.photos/seed/jaipur3/600/400']},{id:4,name:'Palm Breeze Suites',city:'Goa',price:6199,rating:4.8,reviews:201,description:'Large suites, family-friendly cabanas, all-day cafe, and a short walk to the shore.',amenities:['Family rooms','Pool','Breakfast','Spa'],images:['https://picsum.photos/seed/palm1/600/400','https://picsum.photos/seed/palm2/600/400','https://picsum.photos/seed/palm3/600/400']},{id:5,name:'Cedar Peak Lodge',city:'Manali',price:4499,rating:4.5,reviews:113,description:'Scenic balcony rooms, travel desk, and cafe seating with pine valley views.',amenities:['Breakfast','Balcony','Free WiFi','Travel desk'],images:['https://picsum.photos/seed/cedar1/600/400','https://picsum.photos/seed/cedar2/600/400','https://picsum.photos/seed/cedar3/600/400']},{id:6,name:'Royal Haveli Stay',city:'Jaipur',price:3899,rating:4.4,reviews:97,description:'Quiet haveli-style retreat with hand-painted rooms and a compact rooftop dining area.',amenities:['Rooftop dining','WiFi','Breakfast','Couple friendly'],images:['https://picsum.photos/seed/haveli1/600/400','https://picsum.photos/seed/haveli2/600/400','https://picsum.photos/seed/haveli3/600/400']}];
const hotelGrid=document.getElementById('hotelGrid'),resultSummary=document.getElementById('resultSummary'),bookingHotelName=document.getElementById('bookingHotelName'),bookingMeta=document.getElementById('bookingMeta'),roomFare=document.getElementById('roomFare'),taxFare=document.getElementById('taxFare'),totalFare=document.getElementById('totalFare'),reserveBtn=document.getElementById('reserveBtn'),modal=document.getElementById('hotelModal'),modalTitle=document.getElementById('modalTitle'),modalGallery=document.getElementById('modalGallery'),modalCopy=document.getElementById('modalCopy'),modalAmenities=document.getElementById('modalAmenities'),closeModal=document.getElementById('closeModal'),destinationInput=document.getElementById('destinationInput'),searchForm=document.getElementById('searchForm'),themeToggle=document.getElementById('themeToggle');
let activeHotels=[...hotels],selectedHotel=null;
const formatINR=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
function renderHotels(data){hotelGrid.innerHTML=data.map(hotel=>`<article class="hotel-card"><img src="${hotel.images[0]}" alt="${hotel.name}" loading="lazy" width="600" height="400" /><div class="hotel-card-content"><div class="price-row"><div><h3>${hotel.name}</h3><p class="hotel-meta">${hotel.city} · ${hotel.rating} ★ (${hotel.reviews} reviews)</p></div><strong class="hotel-price">${formatINR(hotel.price)}</strong></div><p class="muted">${hotel.description}</p><div class="amenities">${hotel.amenities.map(item=>`<span>${item}</span>`).join('')}</div><div class="card-actions"><button class="secondary-btn details-btn" data-id="${hotel.id}">View details</button><button class="primary-btn select-btn" data-id="${hotel.id}">Choose room</button></div></div></article>`).join('');resultSummary.textContent=`Showing ${data.length} stays`}
function setBooking(hotel){selectedHotel=hotel;const tax=Math.round(hotel.price*.18);bookingHotelName.textContent=hotel.name;bookingMeta.textContent=`${hotel.city} · ${hotel.rating} ★ · 1 Deluxe Room`;roomFare.textContent=formatINR(hotel.price);taxFare.textContent=formatINR(tax);totalFare.textContent=formatINR(hotel.price+tax)}
function openModal(hotel){modalTitle.textContent=hotel.name;modalCopy.textContent=hotel.description;modalGallery.innerHTML=hotel.images.map((src,index)=>`<img src="${src}" alt="${hotel.name} preview ${index+1}" width="600" height="400" loading="lazy" />`).join('');modalAmenities.innerHTML=hotel.amenities.map(item=>`<span>${item}</span>`).join('');modal.showModal()}
function filterHotels(criteria={}){activeHotels=hotels.filter(hotel=>{if(criteria.city&&criteria.city!=='All'&&hotel.city!==criteria.city)return false;if(criteria.rating&&hotel.rating<Number(criteria.rating))return false;if(criteria.price&&hotel.price>=Number(criteria.price))return false;if(criteria.amenity&&!hotel.amenities.includes(criteria.amenity))return false;if(criteria.destination&&!hotel.city.toLowerCase().includes(criteria.destination.toLowerCase()))return false;return true});renderHotels(activeHotels)}
renderHotels(activeHotels);setBooking(hotels[0]);
document.addEventListener('click',event=>{const detailsBtn=event.target.closest('.details-btn'),selectBtn=event.target.closest('.select-btn'),filterChip=event.target.closest('.filter-chip');if(detailsBtn){const hotel=hotels.find(item=>item.id===Number(detailsBtn.dataset.id));openModal(hotel)}if(selectBtn){const hotel=hotels.find(item=>item.id===Number(selectBtn.dataset.id));setBooking(hotel)}if(filterChip){document.querySelectorAll('.filter-chip').forEach(btn=>btn.classList.remove('active'));filterChip.classList.add('active');filterHotels(filterChip.dataset)}});
closeModal.addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{const rect=modal.getBoundingClientRect();const clickedInside=rect.top<=event.clientY&&event.clientY<=rect.bottom&&rect.left<=event.clientX&&event.clientX<=rect.right;if(!clickedInside)modal.close()});
searchForm.addEventListener('submit',event=>{event.preventDefault();filterHotels({destination:destinationInput.value.trim()})});
reserveBtn.addEventListener('click',()=>{if(!selectedHotel)return;reserveBtn.textContent=`Reserved: ${selectedHotel.name}`;reserveBtn.style.background='var(--success)'});
themeToggle.addEventListener('click',()=>{const html=document.documentElement;const nextTheme=html.getAttribute('data-theme')==='dark'?'light':'dark';html.setAttribute('data-theme',nextTheme);document.querySelector('.theme-icon').textContent=nextTheme==='dark'?'☀':'☾'});
